include:
    - ./ordering_agent/docker-compose.dev.yml

services:
    qdrant:
        image: qdrant/qdrant
        container_name: qdrant
        ports:
            - '6333:6333'
            - '6334:6334'
        volumes:
            - qdrant-data:/qdrant/storage

    mysql:
        image: mysql
        container_name: mysql
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - mysql-data:/var/lib/mysql

    storage_automation:
        build:
            context: ./storage
            dockerfile: Dockerfile
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - OPENAI_ORGANIZATION=${OPENAI_ORGANIZATION}

            - QDRANT_URL=http://qdrant:6333
            - QDRANT_COLLECTION_PRODUCTS=${QDRANT_COLLECTION_PRODUCTS}
            - QDRANT_COLLECTION_CUSTOMERS=${QDRANT_COLLECTION_CUSTOMERS}
            - QDRANT_COLLECTION_SHIPPING_METHODS=${QDRANT_COLLECTION_SHIPPING_METHODS}
            - QDRANT_COLLECTION_PAYMENT_METHODS=${QDRANT_COLLECTION_PAYMENT_METHODS}

            - MYSQL_HOST=mysql
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

            - SHOPRENTER_API_BASE_URL=${SHOPRENTER_API_BASE_URL}
            - SHOPRENTER_API_USER=${SHOPRENTER_API_USER}
            - SHOPRENTER_API_PASS=${SHOPRENTER_API_PASS}

            - DEBUG=${DEBUG}

            - UPDATE_STORAGE=${UPDATE_STORAGE}
            - UPDATE_MYSQL=${UPDATE_MYSQL}
            - UPDATE_QDRANT=${UPDATE_QDRANT}
        volumes:
            - ./storage:/app

    gls_print_label_backend:
        build:
            context: ./gls_print_label
            dockerfile: Dockerfile.dev
        environment:
            - GLS_CLIENT_NUMBER=${GLS_CLIENT_NUMBER}
            - GLS_USERNAME=${GLS_USERNAME}
            - GLS_PASSWORD=${GLS_PASSWORD}
            - VITE_GLS_BACKEND_URL=${VITE_GLS_BACKEND_URL}

            - BACKORDER_GUIDE_SPREADSHEET_ID=${BACKORDER_GUIDE_SPREADSHEET_ID}
            - BACKORDER_GUIDE_SPREADSHEET_GID=${BACKORDER_GUIDE_SPREADSHEET_GID}

            - MAIL_MAILER=${MAIL_MAILER}
            - MAIL_DRIVER=${MAIL_DRIVER}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
            - MAIL_FROM_NAME=${MAIL_FROM_NAME}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}

            - XXL_LOGISTICS_BASE_URL=${XXL_LOGISTICS_BASE_URL}
            - XXL_LOGISTICS_EMAIL=${XXL_LOGISTICS_EMAIL}
            - XXL_LOGISTICS_PASSWORD=${XXL_LOGISTICS_PASSWORD}

            - QDRANT_URL=${QDRANT_URL}
            - QDRANT_COLLECTION_FOXPOST=${QDRANT_COLLECTION_FOXPOST}

            - MYSQL_HOST=mysql
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

            - DEBUG=${DEBUG}
            - CHOKIDAR_USEPOLLING=true # Cross platform file update checking
        ports:
            - '8002:8002'
        volumes:
            - ./gls_print_label:/app
            - /app/node_modules # Do not overwrite the container node_modules

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        environment:
            - VITE_PORT=${VITE_PORT}
            - VITE_BACKEND_URL=http://ordering_agent_agent:8001
            - VITE_GLS_BACKEND_URL=http://gls_print_label_backend:8002

            - CHOKIDAR_USEPOLLING=true # Cross platform file update checking
        ports:
            - '${VITE_PORT}:${VITE_PORT}'
        volumes:
            - ./frontend:/app
            - /app/node_modules # Do not overwrite the container node_modules

volumes:
    qdrant-data:
    mysql-data:
