FROM python:3.13-alpine

WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install uv \
    && uv pip install --system --no-cache --upgrade pip \
    && uv pip install --system --no-cache -r requirements.txt

EXPOSE 8000

COPY . .

CMD ["uvicorn", "mcp_server:mcp_server_app", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "120"]
