from sqlalchemy import JSON, Column, Integer, String, Text

from mysql.db import Base


class Order(Base):
    __tablename__ = 'orders'

    href = Column(Text(1024), nullable=True)
    id = Column(String(256), nullable=False, primary_key=True)
    innerId = Column(Text(1024), nullable=True)
    invoiceId = Column(Text(1024), nullable=True)
    invoicePrefix = Column(Text(1024), nullable=True)
    firstname = Column(Text(1024), nullable=True)
    lastname = Column(Text(1024), nullable=True)
    phone = Column(Text(1024), nullable=True)
    fax = Column(Text(1024), nullable=True)
    email = Column(Text(1024), nullable=True)
    shippingFirstname = Column(Text(1024), nullable=True)
    shippingLastname = Column(Text(1024), nullable=True)
    shippingCompany = Column(Text(1024), nullable=True)
    shippingAddress1 = Column(Text(1024), nullable=True)
    shippingAddress2 = Column(Text(1024), nullable=True)
    shippingCity = Column(Text(1024), nullable=True)
    shippingPostcode = Column(Text(1024), nullable=True)
    shippingZoneName = Column(Text(1024), nullable=True)
    shippingCountryName = Column(Text(1024), nullable=True)
    shippingAddressFormat = Column(Text(1024), nullable=True)
    shippingMethodName = Column(Text(1024), nullable=True)
    shippingMethodLocalizedName = Column(Text(1024), nullable=True)
    shippingMethodTaxRate = Column(Text(1024), nullable=True)
    shippingMethodTaxName = Column(Text(1024), nullable=True)
    shippingMethodExtension = Column(Text(1024), nullable=True)
    shippingReceivingPointId = Column(Text(1024), nullable=True)
    paymentFirstname = Column(Text(1024), nullable=True)
    paymentLastname = Column(Text(1024), nullable=True)
    paymentCompany = Column(Text(1024), nullable=True)
    paymentAddress1 = Column(Text(1024), nullable=True)
    paymentAddress2 = Column(Text(1024), nullable=True)
    paymentCity = Column(Text(1024), nullable=True)
    paymentPostcode = Column(Text(1024), nullable=True)
    paymentZoneName = Column(Text(1024), nullable=True)
    paymentCountryName = Column(Text(1024), nullable=True)
    paymentAddressFormat = Column(Text(1024), nullable=True)
    paymentMethodName = Column(Text(1024), nullable=True)
    paymentMethodCode = Column(Text(1024), nullable=True)
    paymentMethodTaxRate = Column(Text(1024), nullable=True)
    paymentMethodTaxName = Column(Text(1024), nullable=True)
    paymentMethodAfter = Column(Text(1024), nullable=True)
    taxNumber = Column(Text(1024), nullable=True)
    comment = Column(Text(1024), nullable=True)
    total = Column(Text(1024), nullable=True)
    value = Column(Text(1024), nullable=True)
    couponTaxRate = Column(Text(1024), nullable=True)
    dateCreated = Column(Text(1024), nullable=True)
    dateUpdated = Column(Text(1024), nullable=True)
    ip = Column(Text(1024), nullable=True)
    pickPackPontShopCode = Column(Text(1024), nullable=True)
    loyaltyPointsTaxRate = Column(Text(1024), nullable=True)
    customer = Column(JSON, nullable=True)
    customerGroup = Column(JSON, nullable=True)
    shippingZone = Column(JSON, nullable=True)
    shippingCountry = Column(JSON, nullable=True)
    paymentZone = Column(JSON, nullable=True)
    paymentCountry = Column(JSON, nullable=True)
    orderStatus = Column(JSON, nullable=True)
    language = Column(JSON, nullable=True)
    currency = Column(JSON, nullable=True)
    shippingMode = Column(JSON, nullable=True)
    coupon = Column(JSON, nullable=True)
    externalInfo = Column(JSON, nullable=True)
    furgefutarWaybill = Column(Integer, nullable=True)
    orderTotals = Column(JSON, nullable=True)
    orderProducts = Column(JSON, nullable=True)
    orderGiftWrappings = Column(JSON, nullable=True)
    orderProductAddons = Column(JSON, nullable=True)
    orderAddressIdentifications = Column(JSON, nullable=True)
    orderCreditCards = Column(JSON, nullable=True)
    print_label_url = Column(Text(1024), nullable=False)

    def __init__(self, order_data):
        self.href = order_data.get('href')
        self.id = order_data.get('id')
        self.innerId = order_data.get('innerId')
        self.invoiceId = order_data.get('invoiceId')
        self.invoicePrefix = order_data.get('invoicePrefix')
        self.firstname = order_data.get('firstname')
        self.lastname = order_data.get('lastname')
        self.phone = order_data.get('phone')
        self.fax = order_data.get('fax')
        self.email = order_data.get('email')
        self.shippingFirstname = order_data.get('shippingFirstname')
        self.shippingLastname = order_data.get('shippingLastname')
        self.shippingCompany = order_data.get('shippingCompany')
        self.shippingAddress1 = order_data.get('shippingAddress1')
        self.shippingAddress2 = order_data.get('shippingAddress2')
        self.shippingCity = order_data.get('shippingCity')
        self.shippingPostcode = order_data.get('shippingPostcode')
        self.shippingZoneName = order_data.get('shippingZoneName')
        self.shippingCountryName = order_data.get('shippingCountryName')
        self.shippingAddressFormat = order_data.get('shippingAddressFormat')
        self.shippingMethodName = order_data.get('shippingMethodName')
        self.shippingMethodLocalizedName = order_data.get(
            'shippingMethodLocalizedName')
        self.shippingMethodTaxRate = order_data.get('shippingMethodTaxRate')
        self.shippingMethodTaxName = order_data.get('shippingMethodTaxName')
        self.shippingMethodExtension = order_data.get(
            'shippingMethodExtension')
        self.shippingReceivingPointId = order_data.get(
            'shippingReceivingPointId')
        self.paymentFirstname = order_data.get('paymentFirstname')
        self.paymentLastname = order_data.get('paymentLastname')
        self.paymentCompany = order_data.get('paymentCompany')
        self.paymentAddress1 = order_data.get('paymentAddress1')
        self.paymentAddress2 = order_data.get('paymentAddress2')
        self.paymentCity = order_data.get('paymentCity')
        self.paymentPostcode = order_data.get('paymentPostcode')
        self.paymentZoneName = order_data.get('paymentZoneName')
        self.paymentCountryName = order_data.get('paymentCountryName')
        self.paymentAddressFormat = order_data.get('paymentAddressFormat')
        self.paymentMethodName = order_data.get('paymentMethodName')
        self.paymentMethodCode = order_data.get('paymentMethodCode')
        self.paymentMethodTaxRate = order_data.get('paymentMethodTaxRate')
        self.paymentMethodTaxName = order_data.get('paymentMethodTaxName')
        self.paymentMethodAfter = order_data.get('paymentMethodAfter')
        self.taxNumber = order_data.get('taxNumber')
        self.comment = order_data.get('comment')
        self.total = order_data.get('total')
        self.value = order_data.get('value')
        self.couponTaxRate = order_data.get('couponTaxRate')
        self.dateCreated = order_data.get('dateCreated')
        self.dateUpdated = order_data.get('dateUpdated')
        self.ip = order_data.get('ip')
        self.pickPackPontShopCode = order_data.get('pickPackPontShopCode')
        self.loyaltyPointsTaxRate = order_data.get('loyaltyPointsTaxRate')
        self.customer = order_data.get('customer')
        self.customerGroup = order_data.get('customerGroup')
        self.shippingZone = order_data.get('shippingZone')
        self.shippingCountry = order_data.get('shippingCountry')
        self.paymentZone = order_data.get('paymentZone')
        self.paymentCountry = order_data.get('paymentCountry')
        self.orderStatus = order_data.get('orderStatus')
        self.language = order_data.get('language')
        self.currency = order_data.get('currency')
        self.shippingMode = order_data.get('shippingMode')
        self.coupon = order_data.get('coupon')
        self.externalInfo = order_data.get('externalInfo')
        self.furgefutarWaybill = order_data.get('furgefutarWaybill')
        self.orderTotals = order_data.get('orderTotals')
        self.orderProducts = order_data.get('orderProducts')
        self.orderGiftWrappings = order_data.get('orderGiftWrappings')
        self.orderProductAddons = order_data.get('orderProductAddons')
        self.orderAddressIdentifications = order_data.get(
            'orderAddressIdentifications')
        self.orderCreditCards = order_data.get('orderCreditCards')

        self.print_label_url = ''
